Repository chromaui/addon-visual-tests, pull requests merged in 2023-08, with the labels that each got.

#30 use mswLoader instead of decorator
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  yarn.lock
Labels: skip-release

#50 Docs: Minor documentation improvements
  Development.md
  README.md
Labels: documentation

#54 Storybook API: use `useAddonState` from `manager-api`
  src/utils/graphQLClient.tsx
  src/utils/useProjectId.ts
  src/utils/useSharedState.ts
Labels: enhancement

#62 upgrade storybook & make development easier
  .storybook/main.ts
  package.json
  src/dev.ts
  yarn.lock
Labels: enhancement

#63 Docs: Adds newly added flags to the documentation
  README.md
Labels: documentation
