Repository chromaui/addon-visual-tests, pull requests merged in 2024-10, with the labels that each got.

#339 Send Slack notification when new version is released on npm
  .github/workflows/release.yml
  package.json
  yarn.lock
Labels: skip-release, patch

#343 Add a prefix to log messages
  package.json
  src/manager.tsx
  src/runChromaticBuild.ts
  yarn.lock
Labels: release, minor

#345 Prevent running tests from Testing Module while there's a warning
  src/TestingModuleDescription.tsx
Labels: release, patch

#346 Fix dependencies to support Storybook >=`8.2.0` explicitly
  CHANGELOG.md
  README.md
  package.json
  src/TestingModuleDescription.tsx
  src/manager.tsx
  src/preset.ts
  yarn.lock
Labels: release, patch, dependencies
