Repository chromaui/addon-visual-tests, pull requests merged in 2024-04, with the labels that each got.

#276 Add link to Visual Tests webpage on Authentication screens
  src/components/BackButton.tsx
  src/components/Screen.tsx
  src/gql/graphql.ts
  src/screens/Authentication/AuthHeader.tsx
  src/screens/Authentication/SetSubdomain.tsx
  src/screens/Authentication/SignIn.tsx
  src/screens/Authentication/Verify.tsx
  src/screens/Authentication/Welcome.tsx
Labels: release, patch

#272 Fix misbehaving in rendering when addon is not active
  src/Panel.tsx
Labels: skip-release, patch

#282 Show error screen when account is suspended
  src/gql/gql.ts
  src/gql/graphql.ts
  src/gql/public-schema.graphql
  src/screens/Errors/AccountSuspended.stories.tsx
  src/screens/Errors/AccountSuspended.tsx
  src/screens/Errors/BuildLimited.stories.tsx
  src/screens/Errors/BuildLimited.tsx
  src/screens/Onboarding/Onboarding.tsx
  src/screens/VisualTests/BuildContext.tsx
  src/screens/VisualTests/VisualTests.tsx
  src/screens/VisualTests/graphql.ts
  src/screens/VisualTests/mocks.ts
Labels: skip-release, minor

#281 Open addon panel when notification is clicked, and pass new `duration` option
  src/SidebarTop.tsx
  src/screens/Authentication/Verify.tsx
  src/screens/VisualTests/VisualTests.tsx
  src/utils/useErrorNotification.ts
Labels: skip-release, minor

#274 Save local state in `sessionStorage` or shared state
  .storybook/main.ts
  .storybook/preview.tsx
  src/Panel.tsx
  src/index.ts
  src/screens/Authentication/Authentication.stories.tsx
  src/screens/Authentication/Authentication.tsx
  src/screens/GuidedTour/GuidedTour.tsx
  src/screens/LinkProject/LinkProject.tsx
  src/screens/Onboarding/Onboarding.stories.tsx
  src/screens/Onboarding/Onboarding.tsx
  src/screens/VisualTests/VisualTests.tsx
  src/types.ts
  src/utils/useProjectId.ts
  src/utils/useSessionState.stories.tsx
  src/utils/useSessionState.ts
  src/utils/useTests.stories.tsx
Labels: release, patch

#285 Tweak messaging for snapshotting new story
  src/screens/VisualTests/BuildResults.tsx
Labels: skip-release, patch

#283 Fix white background on snapshot image thumbnail with transparent `backgroundColor`
  src/components/SnapshotImageThumb.stories.tsx
  src/components/SnapshotImageThumb.tsx
Labels: skip-release, patch

#284 Deeply reset the build progress when starting a new build
  src/buildSteps.ts
  src/runChromaticBuild.ts
Labels: release, patch

#287 Refactor and add telemetry to onboarding screens
  .storybook/preview.tsx
  package.json
  src/Panel.tsx
  src/SidebarTop.tsx
  src/components/SnapshotImage.tsx
  src/components/SuffixInput.tsx
  src/constants.ts
  src/index.ts
  src/screens/Authentication/Authentication.tsx
  src/screens/Authentication/SetSubdomain.tsx
  src/screens/Errors/AccountSuspended.tsx
  src/screens/Errors/BuildError.tsx
  src/screens/Errors/GitNotFound.tsx
  src/screens/GuidedTour/GuidedTour.tsx
  src/screens/LinkProject/LinkProject.tsx
  src/screens/LinkProject/LinkedProject.tsx
  src/screens/LinkProject/LinkingProjectFailed.tsx
  src/screens/Onboarding/CatchAChange.tsx
  src/screens/Onboarding/CatchAChangeComplete.tsx
  src/screens/Onboarding/InitialBuild.tsx
  src/screens/Onboarding/InitialBuildComplete.tsx
  src/screens/Onboarding/Onboarding.stories.tsx
  src/screens/Onboarding/Onboarding.tsx
  src/screens/Uninstalled/Uninstalled.tsx
  src/screens/VisualTests/BuildEyebrow.tsx
  src/screens/VisualTests/BuildResults.tsx
  src/screens/VisualTests/NoBuild.tsx
  src/screens/VisualTests/VisualTests.tsx
  src/screens/VisualTests/Warnings.tsx
  src/utils/TelemetryContext.tsx
  src/utils/useBuildEvents.ts
  yarn.lock
Labels: release, patch

#289 Fix bundling strategy of tsup
  package.json
  preset.js
  src/index.ts
  src/preset.ts
  tsup.config.ts
Labels: release, patch
