Repository chromaui/addon-visual-tests, pull requests merged in 2024-01, with the labels that each got.

#158 UI to uninstall addon
  .eslintrc.cjs
  .storybook/main.ts
  .vscode/settings.json
  package.json
  src/Panel.tsx
  src/components/BackButton.tsx
  src/components/SidebarTopButton.tsx
  src/components/SnapshotImage.stories.tsx
  src/components/Stack.tsx
  src/constants.ts
  src/index.ts
  src/screens/Authentication/Authentication.stories.tsx
  src/screens/Authentication/Authentication.tsx
  src/screens/Authentication/SetSubdomain.tsx
  src/screens/Authentication/SignIn.tsx
  src/screens/Authentication/Verify.tsx
  src/screens/Authentication/Welcome.tsx
  src/screens/GitNotFound/GitNotFound.stories.tsx
  src/screens/LinkProject/LinkProject.stories.ts
  src/screens/LinkProject/LinkedProject.tsx
  src/screens/LinkProject/LinkingProjectFailed.stories.ts
  src/screens/VisualTests/BuildEyebrow.stories.ts
  src/screens/VisualTests/BuildResults.tsx
  src/screens/VisualTests/NoBuild.tsx
  src/screens/VisualTests/RenderSettings.stories.tsx
  src/screens/VisualTests/SnapshotComparison.stories.tsx
  src/screens/VisualTests/SnapshotControls.tsx
  src/screens/VisualTests/StoryInfo.tsx
  src/screens/VisualTests/VisualTests.stories.tsx
  src/screens/VisualTests/Warnings.tsx
  yarn.lock
Labels: skip-release, major

#157 Release v1.0.0
  .vscode/settings.json
Labels: release, major

#160 Revert "UI to uninstall addon"
  .eslintrc.cjs
  .storybook/main.ts
  .vscode/settings.json
  package.json
  src/Panel.tsx
  src/components/BackButton.tsx
  src/components/SidebarTopButton.tsx
  src/components/SnapshotImage.stories.tsx
  src/components/Stack.tsx
  src/constants.ts
  src/index.ts
  src/screens/Authentication/Authentication.stories.tsx
  src/screens/Authentication/Authentication.tsx
  src/screens/Authentication/SetSubdomain.tsx
  src/screens/Authentication/SignIn.tsx
  src/screens/Authentication/Verify.tsx
  src/screens/Authentication/Welcome.tsx
  src/screens/GitNotFound/GitNotFound.stories.tsx
  src/screens/LinkProject/LinkProject.stories.ts
  src/screens/LinkProject/LinkedProject.tsx
  src/screens/LinkProject/LinkingProjectFailed.stories.ts
  src/screens/VisualTests/BuildEyebrow.stories.ts
  src/screens/VisualTests/BuildResults.tsx
  src/screens/VisualTests/NoBuild.tsx
  src/screens/VisualTests/RenderSettings.stories.tsx
  src/screens/VisualTests/SnapshotComparison.stories.tsx
  src/screens/VisualTests/SnapshotControls.tsx
  src/screens/VisualTests/StoryInfo.tsx
  src/screens/VisualTests/VisualTests.stories.tsx
  src/screens/VisualTests/Warnings.tsx
  yarn.lock
Labels: skip-release, patch
