Repository chromaui/addon-visual-tests, pull requests merged in 2024-03, with the labels that each got.

#198 Ensure onboarding is triggered when query param is set
  src/screens/VisualTests/VisualTests.tsx
Labels: release, patch

#215 Require PR labels before merging
  .github/workflows/check-labels.yml
Labels: skip-release, patch

#217 Update text style and use it more consistently
  src/components/Box.tsx
  src/components/BuildProgressBarInline.tsx
  src/components/BuildProgressLabel.tsx
  src/components/SnapshotImage.tsx
  src/components/Text.tsx
  src/components/layout.tsx
  src/screens/Authentication/SetSubdomain.tsx
  src/screens/Authentication/SignIn.tsx
  src/screens/Authentication/Verify.tsx
  src/screens/Authentication/Welcome.tsx
  src/screens/Errors/BuildError.tsx
  src/screens/Errors/BuildLimited.tsx
  src/screens/Errors/GitNotFound.tsx
  src/screens/LinkProject/LinkProject.tsx
  src/screens/LinkProject/LinkedProject.tsx
  src/screens/LinkProject/LinkingProjectFailed.tsx
  src/screens/NoDevServer/NoDevServer.tsx
  src/screens/Onboarding/Onboarding.tsx
  src/screens/Uninstalled/Uninstalled.tsx
  src/screens/VisualTests/BuildResults.tsx
  src/screens/VisualTests/NoBuild.tsx
  src/screens/VisualTests/SnapshotComparison.tsx
  src/screens/VisualTests/SnapshotControls.tsx
Labels: release, patch

#216 Fixed up ActionButton and the Mode/Browser selectors
  src/components/ActionButton.tsx
  src/components/BrowserSelector.tsx
  src/components/IconButton.tsx
  src/components/ModeSelector.tsx
  src/screens/VisualTests/SnapshotControls.tsx
Labels: enhancement, skip-release, patch

#220 Set Zip to true by default on config updates
  src/index.ts
Labels: release, patch

#221 Don't show extra border when no config is available
  src/components/Screen.stories.tsx
  src/screens/VisualTests/Configuration.tsx
Labels: release, patch

#222 Normalize `configDir` before comparing
  src/index.ts
Labels: release, patch

#218 Only use criteria to select mode when story first loads
  src/gql/graphql.ts
  src/screens/VisualTests/BuildResultsFooter.tsx
  src/screens/VisualTests/SnapshotComparison.stories.tsx
  src/screens/VisualTests/SnapshotComparison.tsx
  src/screens/VisualTests/SnapshotControls.tsx
  src/screens/VisualTests/VisualTests.stories.tsx
  src/utils/useTests.stories.tsx
  src/utils/useTests.test.ts
  src/utils/useTests.ts
Labels: release, patch

#223 Fix dramatic layout bug during onboarding
  src/components/Text.tsx
  src/components/layout.tsx
  src/screens/Onboarding/Onboarding.tsx
Labels: bug, release, patch

#225 Create `SECURITY.md`
  SECURITY.md
Labels: skip-release, patch

#224 Setup GitHub issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: skip-release, patch

#226 Update guided tour tooltip to match Storybook
  src/screens/GuidedTour/Tooltip.tsx
Labels: enhancement, release, patch

#219 VTA: Fix tooltip spacing
  src/components/BrowserSelector.tsx
  src/components/ModeSelector.tsx
  src/components/SidebarTopButton.tsx
  src/components/TooltipMenu.tsx
  src/components/TooltipNote.tsx
  src/screens/VisualTests/BuildResultsFooter.tsx
  src/screens/VisualTests/SnapshotControls.tsx
Labels: enhancement, release, patch

#227 Update addon metadata
  README.md
  package.json
Labels: skip-release, patch
