Repository chromaui/addon-visual-tests, pull requests merged in 2024-02, with the labels that each got.

#144 Visual Test Addon Onboarding behind query param
  .storybook/preview.tsx
  package.json
  public/Snapshot-Preview.png
  public/example-button-noargs.png
  public/mockServiceWorker.js
  src/SidebarBottom.tsx
  src/SidebarTop.tsx
  src/components/Container.tsx
  src/components/SidebarToggleButton.tsx
  src/components/SidebarTopButton.tsx
  src/components/SnapshotImageThumb.stories.tsx
  src/components/SnapshotImageThumb.tsx
  src/constants.ts
  src/gql/gql.ts
  src/gql/graphql.ts
  src/screens/GitNotFound/GitNotFound.tsx
  src/screens/GuidedTour/Confetti.tsx
  src/screens/GuidedTour/GuidedTour.tsx
  src/screens/GuidedTour/PulsatingEffect.tsx
  src/screens/GuidedTour/Tooltip.tsx
  src/screens/LinkProject/LinkProject.tsx
  src/screens/LinkProject/LinkedProject.tsx
  src/screens/LinkProject/LinkingProjectFailed.tsx
  src/screens/Onboarding/Onboarding.stories.tsx
  src/screens/Onboarding/Onboarding.tsx
  src/screens/Onboarding/onboarding-adjust-size.png
  src/screens/Onboarding/onboarding-color-palette.png
  src/screens/Onboarding/onboarding-embiggen.png
  src/screens/Onboarding/onboarding-layout.png
  src/screens/Onboarding/onboarding-shift-color-palette.png
  src/screens/VisualTests/BuildContext.tsx
  src/screens/VisualTests/BuildResults.tsx
  src/screens/VisualTests/NoBuild.tsx
  src/screens/VisualTests/RenderSettings.tsx
  src/screens/VisualTests/SnapshotComparison.stories.tsx
  src/screens/VisualTests/SnapshotComparison.tsx
  src/screens/VisualTests/SnapshotControls.stories.tsx
  src/screens/VisualTests/SnapshotControls.tsx
  src/screens/VisualTests/VisualTests.stories.tsx
  src/screens/VisualTests/VisualTests.tsx
  src/screens/VisualTests/graphql.ts
  src/screens/VisualTests/mocks.ts
  src/utils/storyData.ts
  tsconfig.json
  tsup.config.ts
  types.d.ts
  yarn.lock
Labels: skip-release, minor

#164 Release 0.1.0
  CHANGELOG.md
Labels: minor

#165 UI to uninstall addon
  .eslintrc.cjs
  .vscode/settings.json
  package.json
  src/Panel.tsx
  src/components/SidebarTopButton.tsx
  src/components/SnapshotImage.stories.tsx
  src/components/Stack.tsx
  src/constants.ts
  src/index.ts
  src/screens/Authentication/Authentication.stories.tsx
  src/screens/Authentication/Authentication.tsx
  src/screens/Authentication/SetSubdomain.tsx
  src/screens/Authentication/SignIn.tsx
  src/screens/Authentication/Verify.tsx
  src/screens/Authentication/Welcome.tsx
  src/screens/GitNotFound/GitNotFound.stories.tsx
  src/screens/GuidedTour/Confetti.tsx
  src/screens/GuidedTour/Tooltip.tsx
  src/screens/LinkProject/LinkProject.stories.ts
  src/screens/LinkProject/LinkedProject.tsx
  src/screens/LinkProject/LinkingProjectFailed.stories.ts
  src/screens/Onboarding/Onboarding.stories.tsx
  src/screens/VisualTests/BuildEyebrow.stories.ts
  src/screens/VisualTests/BuildResults.tsx
  src/screens/VisualTests/NoBuild.tsx
  src/screens/VisualTests/RenderSettings.stories.tsx
  src/screens/VisualTests/SnapshotComparison.stories.tsx
  src/screens/VisualTests/SnapshotControls.tsx
  src/screens/VisualTests/StoryInfo.tsx
  src/screens/VisualTests/VisualTests.stories.tsx
  src/screens/VisualTests/Warnings.tsx
  yarn.lock
Labels: major

#166 Fix SB version duplication in dependencies
  package.json
  yarn.lock
Labels: release, patch

#168 Various CSS and icon fixes
  package.json
  src/components/Accordions.tsx
  src/components/ActionButton.tsx
  src/components/BrowserSelector.tsx
  src/components/Button.tsx
  src/components/FooterMenu.tsx
  src/components/ModeSelector.tsx
  src/components/SidebarTopButton.tsx
  src/components/SnapshotImage.tsx
  src/components/SnapshotImageThumb.tsx
  src/components/icons/ArrowIcon.tsx
  src/components/icons/StatusIcon.tsx
  src/screens/Authentication/Welcome.tsx
  src/screens/LinkProject/LinkProject.tsx
  src/screens/LinkProject/LinkedProject.tsx
  src/screens/Onboarding/Onboarding.tsx
  src/screens/VisualTests/BuildEyebrow.tsx
  src/screens/VisualTests/BuildResults.tsx
  src/screens/VisualTests/BuildResultsFooter.tsx
  src/screens/VisualTests/NoBuild.tsx
  src/screens/VisualTests/RenderSettings.tsx
  src/screens/VisualTests/SnapshotComparison.tsx
  src/screens/VisualTests/SnapshotControls.tsx
  src/screens/VisualTests/StoryInfo.tsx
  src/screens/VisualTests/Warnings.tsx
  yarn.lock
Labels: release, patch

#172 QA Fast Follows
  .storybook/preview.tsx
  package.json
  src/Panel.tsx
  src/components/FooterMenu.tsx
  src/runChromaticBuild.ts
  src/screens/Authentication/Authentication.tsx
  src/screens/Authentication/Welcome.tsx
  src/screens/GitNotFound/GitNotFound.tsx
  src/screens/Uninstalled/UninstallContext.tsx
  src/screens/Uninstalled/Uninstalled.stories.tsx
  src/screens/Uninstalled/Uninstalled.tsx
  src/screens/VisualTests/VisualTests.stories.tsx
  yarn.lock
Labels: release, minor

#174 Remove @storybook/icons from externals
  tsup.config.ts
Labels: release, patch

#177 Update README.md
  README.md
Labels: documentation, skip-release

#181 Fix kebab-case `box-shadow` to proper `boxShadow`
  src/components/design-system/shared/styles.ts
Labels: bug, release, patch

#176 Display chromatic config and suggestion in UI panel
  src/SidebarTop.tsx
  src/components/FooterMenu.tsx
  src/components/FooterSection.tsx
  src/components/Screen.stories.tsx
  src/components/Screen.tsx
  src/components/SidebarTopButton.stories.tsx
  src/components/SidebarTopButton.tsx
  src/components/StatusDot.tsx
  src/constants.ts
  src/index.ts
  src/runChromaticBuild.ts
  src/screens/GitNotFound/GitNotFound.stories.tsx
  src/screens/VisualTests/Configuration.tsx
  src/screens/VisualTests/ControlsContext.tsx
  src/types.ts
  src/utils/withSetup.tsx
  src/utils/withSharedState.tsx
Labels: release, minor
