Repository chromaui/addon-visual-tests, pull requests merged in 2025-08, with the labels that each got.

#384 Add support for Storybook 9.2
  package.json
  yarn.lock
Labels: release, patch

#380 Release 4.1.0
  eslint.config.mjs
  package.json
  scripts/prepublish-checks.mjs
  src/Panel.tsx
  src/components/BrowserSelector.stories.ts
  src/components/BrowserSelector.tsx
  src/components/ModeSelector.stories.ts
  src/components/ModeSelector.tsx
  src/components/StatusDot.tsx
  src/gql/graphql.ts
  src/gql/public-schema.graphql
  src/types.ts
  src/utils/aggregateResult.ts
  src/utils/useTests.ts
  yarn.lock
Labels: release, minor

#385 Chore: Fix package.json
  package.json
Labels: release, patch

#386 Release 4.1.0
  package.json
Labels: release, minor

#389 Broaden version-range for storybook peerDependency
  package.json
  yarn.lock
Labels: release, patch, dependencies
