Repository chromaui/addon-visual-tests, pull requests merged in 2025-02, with the labels that each got.

#355 Change to Storybook 9.0.0 (+alpha) compatibility
  package.json
  yarn.lock
Labels: release, major, dependencies

#356 add sb canary compatibility
  package.json
  yarn.lock
Labels: bug, release, patch

#357 Debug release
  .github/workflows/release.yml
Labels: release, patch
