Repository chromaui/addon-visual-tests, pull requests merged in 2025-03, with the labels that each got.

#360 Fix GraphQL codegen setup
  .prettierignore
  .vscode/settings.json
  package.json
  src/gql/fragment-masking.ts
  src/gql/gql.ts
  src/gql/index.ts
  tsconfig.json
  yarn.lock
Labels: skip-release, patch

#362 Formatting
  .github/workflows/chromatic.yml
  .github/workflows/test.yml
  .prettierignore
  .storybook/main.ts
  .storybook/preview.tsx
  codegen.ts
  package.json
  scripts/prepublish-checks.mjs
  src/utils/sha256.js
  tsup.config.ts
  vite.config.ts
Labels: skip-release, patch

#363 Fix SSO url
  .storybook/preview.tsx
  src/AuthContext.tsx
  src/Panel.tsx
  src/components/FooterMenu.tsx
  src/screens/Authentication/Authentication.tsx
Labels: release, patch

#364 Update usages to match Storybook 9.0.0-alpha.4
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  src/components/BrowserSelector.stories.ts
  src/components/ModeSelector.stories.ts
  src/components/SidebarBottom.stories.tsx
  src/components/SidebarToggleButton.stories.ts
  src/components/SidebarTopButton.stories.tsx
  src/components/TooltipMenu.stories.tsx
  src/manager.tsx
  src/screens/Authentication/Authentication.stories.tsx
  src/screens/LinkProject/LinkProject.stories.ts
  src/screens/LinkProject/LinkedProject.stories.ts
  src/screens/VisualTests/BuildEyebrow.stories.ts
  src/screens/VisualTests/SnapshotComparison.stories.tsx
  src/screens/VisualTests/SnapshotControls.stories.tsx
  src/screens/VisualTests/StoryInfo.stories.tsx
  src/screens/VisualTests/VisualTests.stories.tsx
  src/utils/action.ts
  yarn.lock
Labels: enhancement, skip-release, patch
