Repository chromaui/addon-visual-tests, pull requests merged in 2025-05, with the labels that each got.

#370 Only run tests when possible
  src/TestProviderRender.tsx
Labels: release, patch

#372 Onboarding: Replace `react-confetti` with `@neoconfetti/react`
  package.json
  src/screens/GuidedTour/Confetti.tsx
  src/screens/GuidedTour/GuidedTour.tsx
  yarn.lock
Labels: skip-release, patch, dependencies

#371 Onboarding: Fix Git initialization problem
  src/Panel.tsx
  src/components/Box.tsx
  src/preset.ts
  src/screens/Errors/GitNotFound.tsx
Labels: bug, skip-release, patch

#368 Remove @storybook/addon-blocks
  README.md
  package.json
  yarn.lock
Labels: skip-release, major

#375 Handle missing git user.email config
  src/screens/Errors/GitError.stories.tsx
  src/screens/Errors/GitError.tsx
Labels: skip-release, minor

#376 Upgrade `chromatic` to v12.0.0
  package.json
  src/constants.ts
  src/preset.ts
  src/runChromaticBuild.ts
  yarn.lock
Labels: release, patch
